
package my.demo.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorSoap", targetNamespace = "http://model.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorSoap {


    /**
     * Adds two integers. This is a test WebService. ©DNE Online
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add", action = "http://model.org/Add")
    @WebResult(name = "AddResult", targetNamespace = "http://model.org/")
    @RequestWrapper(localName = "Add", targetNamespace = "http://model.org/", className = "org.model.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://model.org/", className = "org.model.AddResponse")
    public int add(
        @WebParam(name = "intA", targetNamespace = "http://model.org/")
        int intA,
        @WebParam(name = "intB", targetNamespace = "http://model.org/")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Subtract", action = "http://model.org/Subtract")
    @WebResult(name = "SubtractResult", targetNamespace = "http://model.org/")
    @RequestWrapper(localName = "Subtract", targetNamespace = "http://model.org/", className = "org.model.Subtract")
    @ResponseWrapper(localName = "SubtractResponse", targetNamespace = "http://model.org/", className = "org.model.SubtractResponse")
    public int subtract(
        @WebParam(name = "intA", targetNamespace = "http://model.org/")
        int intA,
        @WebParam(name = "intB", targetNamespace = "http://model.org/")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Multiply", action = "http://model.org/Multiply")
    @WebResult(name = "MultiplyResult", targetNamespace = "http://model.org/")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://model.org/", className = "org.model.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://model.org/", className = "org.model.MultiplyResponse")
    public int multiply(
        @WebParam(name = "intA", targetNamespace = "http://model.org/")
        int intA,
        @WebParam(name = "intB", targetNamespace = "http://model.org/")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Divide", action = "http://model.org/Divide")
    @WebResult(name = "DivideResult", targetNamespace = "http://model.org/")
    @RequestWrapper(localName = "Divide", targetNamespace = "http://model.org/", className = "org.model.Divide")
    @ResponseWrapper(localName = "DivideResponse", targetNamespace = "http://model.org/", className = "org.model.DivideResponse")
    public int divide(
        @WebParam(name = "intA", targetNamespace = "http://model.org/")
        int intA,
        @WebParam(name = "intB", targetNamespace = "http://model.org/")
        int intB);

}
